name: Verify
on:
  workflow_call:
    inputs:
      brakeman:
        type: boolean
      bundler-audit:
        type: boolean
      run-before-test:
        type: string

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.17.0
          cache: "yarn"
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bundle exec rubocop --parallel

          # bundle exec stylelint
          # bundle exec prettier
          # bundle exec eslint
      - name: Run security checks - brakeman
        id: brakeman
        if: ${{ inputs.brakeman == true }}
        run: |
          bundle exec brakeman -q -w2
      - name: Run security checks - bundler-audit
        id: bundler-audit
        if: ${{ inputs.bundler-audit == true }}
        run: |
          bundle exec bundler-audit --update

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.17.0
          cache: "yarn"
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          ${{ inputs.run-before-test }}
          bundle exec rails db:setup

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec
