name: Verify
on:
  workflow_call:
    inputs:
      brakeman:
        type: boolean
      bundler-audit:
        type: boolean

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
    outputs:
      brakeman: ${{ steps.brakeman.inputs.brakeman }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.13.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Run linters
        run: |
          bundle exec rubocop --parallel

          # bundle exec stylelint
          # bundle exec prettier
          # bundle exec eslint
      - name: Run security checks - brakeman
        id: brakeman
        if: ${{ inputs.brakeman == true }}
        run: |
          bundle exec brakeman -q -w2
      - name: Run security checks - bundler-audit
        id: bundler-audit
        if: ${{ inputs.bundler-audit == true }}
        run: |
          bundle exec bundler-audit --update

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.13.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run: |
          bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec
